local function setup_permission_groups()
	local permission_groups = game.permissions
	local admin = permission_groups.get_group("Admin") or permission_groups.create_group("Admin")
	local owner = permission_groups.get_group("Owner") or permission_groups.create_group("Owner")
	local guest = permission_groups.get_group("Guest") or permission_groups.create_group("Guest")

	if not admin or not owner or not guest then
		error("Failed to create permission groups")
	end

	-- Admins can do everything
	admin.set_allows_action(defines.input_action.write_to_console, true)

	-- Owner can do everything except adminastrative actions
	owner.set_allows_action(defines.input_action.add_permission_group, false)
	owner.set_allows_action(defines.input_action.admin_action, false)
	owner.set_allows_action(defines.input_action.change_multiplayer_config, false)
	owner.set_allows_action(defines.input_action.delete_permission_group, false)
	owner.set_allows_action(defines.input_action.edit_permission_group, false)
	owner.set_allows_action(defines.input_action.mod_settings_changed, false)
	owner.set_allows_action(defines.input_action.set_research_finished_stops_game, false)
	owner.set_allows_action(defines.input_action.toggle_map_editor, false)
	owner.set_allows_action(defines.input_action.write_to_console, true)

	-- Guests can only do read-only and non-griefing stuff
	guest.set_allows_action(defines.input_action.activate_cut, false)
	guest.set_allows_action(defines.input_action.activate_paste, false)
	guest.set_allows_action(defines.input_action.add_permission_group, false)
	guest.set_allows_action(defines.input_action.add_train_station, false)
	guest.set_allows_action(defines.input_action.admin_action, false)
	guest.set_allows_action(defines.input_action.begin_mining, false)
	guest.set_allows_action(defines.input_action.begin_mining_terrain, false)
	guest.set_allows_action(defines.input_action.build, false)
	guest.set_allows_action(defines.input_action.build_rail, false)
	guest.set_allows_action(defines.input_action.build_terrain, false)
	guest.set_allows_action(defines.input_action.cancel_craft, false)
	guest.set_allows_action(defines.input_action.cancel_deconstruct, false)
	guest.set_allows_action(defines.input_action.cancel_research, false)
	guest.set_allows_action(defines.input_action.cancel_upgrade, false)
	guest.set_allows_action(defines.input_action.change_arithmetic_combinator_parameters, false)
	guest.set_allows_action(defines.input_action.change_decider_combinator_parameters, false)
	guest.set_allows_action(defines.input_action.change_entity_label, false)
	guest.set_allows_action(defines.input_action.change_item_description, false)
	guest.set_allows_action(defines.input_action.change_item_label, false)
	guest.set_allows_action(defines.input_action.change_multiplayer_config, false)
	guest.set_allows_action(defines.input_action.change_programmable_speaker_alert_parameters, false)
	guest.set_allows_action(defines.input_action.change_programmable_speaker_circuit_parameters, false)
	guest.set_allows_action(defines.input_action.change_programmable_speaker_parameters, false)
	guest.set_allows_action(defines.input_action.change_shooting_state, false)
	guest.set_allows_action(defines.input_action.change_train_stop_station, false)
	guest.set_allows_action(defines.input_action.change_train_wait_condition, false)
	guest.set_allows_action(defines.input_action.change_train_wait_condition_data, false)
	guest.set_allows_action(defines.input_action.connect_rolling_stock, false)
	guest.set_allows_action(defines.input_action.deconstruct, false)
	guest.set_allows_action(defines.input_action.delete_blueprint_library, false)
	guest.set_allows_action(defines.input_action.delete_blueprint_record, false)
	guest.set_allows_action(defines.input_action.delete_custom_tag, false)
	guest.set_allows_action(defines.input_action.delete_permission_group, false)
	guest.set_allows_action(defines.input_action.destroy_item, false)
	guest.set_allows_action(defines.input_action.destroy_opened_item, false)
	guest.set_allows_action(defines.input_action.disconnect_rolling_stock, false)
	guest.set_allows_action(defines.input_action.drag_train_schedule, false)
	guest.set_allows_action(defines.input_action.drag_train_wait_condition, false)
	guest.set_allows_action(defines.input_action.drop_blueprint_record, false)
	guest.set_allows_action(defines.input_action.drop_item, false)
	guest.set_allows_action(defines.input_action.edit_custom_tag, false)
	guest.set_allows_action(defines.input_action.edit_permission_group, false)
	guest.set_allows_action(defines.input_action.fast_entity_split, false)
	guest.set_allows_action(defines.input_action.fast_entity_transfer, false)
	guest.set_allows_action(defines.input_action.flush_opened_entity_fluid, false)
	guest.set_allows_action(defines.input_action.flush_opened_entity_specific_fluid, false)
	guest.set_allows_action(defines.input_action.go_to_train_station, false)
	guest.set_allows_action(defines.input_action.launch_rocket, false)
	guest.set_allows_action(defines.input_action.market_offer, false)
	guest.set_allows_action(defines.input_action.mod_settings_changed, false)
	guest.set_allows_action(defines.input_action.paste_entity_settings, false)
	guest.set_allows_action(defines.input_action.place_equipment, false)
	guest.set_allows_action(defines.input_action.remove_cables, false)
	guest.set_allows_action(defines.input_action.remove_train_station, false)
	guest.set_allows_action(defines.input_action.reset_assembling_machine, false)
	guest.set_allows_action(defines.input_action.reset_item, false)
	guest.set_allows_action(defines.input_action.rotate_entity, false)
	guest.set_allows_action(defines.input_action.send_spidertron, false)
	guest.set_allows_action(defines.input_action.set_auto_launch_rocket, false)
	guest.set_allows_action(defines.input_action.set_behavior_mode, false)
	guest.set_allows_action(defines.input_action.set_car_weapons_control, false)
	guest.set_allows_action(defines.input_action.set_circuit_condition, false)
	guest.set_allows_action(defines.input_action.set_circuit_mode_of_operation, false)
	guest.set_allows_action(defines.input_action.set_entity_color, false)
	guest.set_allows_action(defines.input_action.set_entity_energy_property, false)
	guest.set_allows_action(defines.input_action.set_entity_logistic_trash_filter_item, false)
	guest.set_allows_action(defines.input_action.set_filter, false)
	guest.set_allows_action(defines.input_action.set_heat_interface_mode, false)
	guest.set_allows_action(defines.input_action.set_heat_interface_temperature, false)
	guest.set_allows_action(defines.input_action.set_infinity_container_filter_item, false)
	guest.set_allows_action(defines.input_action.set_infinity_container_remove_unfiltered_items, false)
	guest.set_allows_action(defines.input_action.set_infinity_pipe_filter, false)
	guest.set_allows_action(defines.input_action.set_inserter_max_stack_size, false)
	guest.set_allows_action(defines.input_action.set_inventory_bar, false)
	guest.set_allows_action(defines.input_action.set_linked_container_link_i_d, false)
	guest.set_allows_action(defines.input_action.set_logistic_filter_item, false)
	guest.set_allows_action(defines.input_action.set_logistic_filter_signal, false)
	guest.set_allows_action(defines.input_action.set_recipe_notifications, false)
	guest.set_allows_action(defines.input_action.set_request_from_buffers, false)
	guest.set_allows_action(defines.input_action.set_research_finished_stops_game, false)
	guest.set_allows_action(defines.input_action.set_signal, false)
	guest.set_allows_action(defines.input_action.set_splitter_priority, false)
	guest.set_allows_action(defines.input_action.set_train_stopped, false)
	guest.set_allows_action(defines.input_action.set_trains_limit, false)
	guest.set_allows_action(defines.input_action.set_vehicle_automatic_targeting_parameters, false)
	guest.set_allows_action(defines.input_action.setup_assembling_machine, false)
	guest.set_allows_action(defines.input_action.spawn_item, false)
	guest.set_allows_action(defines.input_action.start_research, false)
	guest.set_allows_action(defines.input_action.switch_connect_to_logistic_network, false)
	guest.set_allows_action(defines.input_action.switch_constant_combinator_state, false)
	guest.set_allows_action(defines.input_action.switch_inserter_filter_mode_state, false)
	guest.set_allows_action(defines.input_action.switch_power_switch_state, false)
	guest.set_allows_action(defines.input_action.switch_to_rename_stop_gui, false)
	guest.set_allows_action(defines.input_action.take_equipment, false)
	guest.set_allows_action(defines.input_action.toggle_driving, false)
	guest.set_allows_action(defines.input_action.toggle_enable_vehicle_logistics_while_moving, false)
	guest.set_allows_action(defines.input_action.toggle_entity_logistic_requests, false)
	guest.set_allows_action(defines.input_action.toggle_map_editor, false)
	guest.set_allows_action(defines.input_action.undo, false)
	guest.set_allows_action(defines.input_action.upgrade, false)
	guest.set_allows_action(defines.input_action.use_artillery_remote, false)
	guest.set_allows_action(defines.input_action.use_item, false)
	guest.set_allows_action(defines.input_action.wire_dragging, false)
	guest.set_allows_action(defines.input_action.write_to_console, true)
end

return setup_permission_groups
