name: CI

on:
  push:
  pull_request:
  create:
    tags:
      - v*

  workflow_dispatch:

jobs:
  visualizer:
    runs-on: ubuntu-latest
    name: Visualizer
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Update diagram
      uses: githubocto/repo-visualizer@0.7.1
      with:
        output_file: "images/diagram.svg"
        excluded_paths: "dist,node_modules,package-lock.json,.luacheckrc"
  jslint:
    name: Eslint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm i --no-optional
    - run: npm i eslint eslint-plugin-node
    - run: npm run lint
  lualint:
    name: Luacheck
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: nebularg/actions-luacheck@v1.1.0
      with:
        files: module/
        annotate: "error"
  publish:
    needs: [jslint, lualint]
    name: "Publish to npm"
    runs-on: ubuntu-latest

    if: github.event.ref_type == 'tag' && startsWith(github.event.ref, 'v')
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm i --no-optional
    - run: npm run prepare
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
