name: CI

on:
  push:
  # pull_request:
  create:
    tags:
      - v*

  workflow_dispatch:

jobs:
  jslint:
    name: Eslint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - run: npm i -g pnpm
    - run: pnpm i --no-optional
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - run: pnpm i eslint eslint-plugin-node
    - run: pnpm run lint
  lualint:
    name: Luacheck
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Danielv123/actions-luacheck@patch-1
      with:
        files: module/
        annotate: "error"
  publish:
    needs: [jslint, lualint]
    name: "Publish to npm"
    runs-on: ubuntu-latest

    if: github.event.ref_type == 'tag' && startsWith(github.event.ref, 'v')
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - run: npm i -g pnpm
    - run: pnpm i --no-optional
    - run: pnpm run prepare
    - run: pnpm publish --access public --no-git-checks
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
