name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@controller
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: "images/diagram.svg"
          excluded_paths: "dist,node_modules,package-lock.json,.luacheckrc"
