name: lua check

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  lualint:
	runs-on: ubuntu-latest

	steps:
	  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
	  - uses: actions/checkout@v2

	  - uses: nebularg/actions-luacheck@v1.1.0
		with:
		  files: module/
		  annotate: "error"
